### ISSUE TITLE
Permissions crash on Android Marshmallow

### ISSUE THREAD

**Issue by JolandaVerhoef** [onesky/auto-screenshot-android#9] opened 2015-11-17 13:22 UTC
When trying to run the app on Android M, it crashes with the following stack trace:
```
java.lang.RuntimeException: Unable to create service com.oneskyapp.screenshot.ScreenshotButtonService: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@9b3f68b -- permission denied for this window type
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2887)
    at android.app.ActivityThread.-wrap4(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@9b3f68b -- permission denied for this window type
    at android.view.ViewRootImpl.setView(ViewRootImpl.java:591)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
    at com.oneskyapp.screenshot.ScreenshotButtonService.onCreate(ScreenshotButtonService.java:63)
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:2877)
    at android.app.ActivityThread.-wrap4(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1427) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

This seems like the same error as the Intercom library had before, see https://github.com/intercom/intercom-android/issues/116

It is caused by the fact that the permission `SYSTEM_ALERT_WINDOW` can't be requested directly anymore in Android M.

**Comment by bretdabaker** [comment] 2015-11-20 17:47
I have removed dependency on `SYSTEM_ALERT_WINDOW` permission in the new release:

https://github.com/onesky/auto-screenshot-android/releases/tag/v0.7.2

Let me know if it works for you.

**Comment by bretdabaker** [comment] 2015-11-27 07:59
I am closing this issue for now, please reopen if you are still experiencing the problem.

**Closed by bretdabaker** 2015-11-27 07:59 UTC

**Comment by khuranakaran** [comment] 2015-12-07 13:01
anyone found the solution to get rid of this crash?

**Comment by bretdabaker** [comment] 2015-12-10 03:43
@khuranakaran are you still getting crashes with the latest release v0.7.2? If so please reopen the issue.

**Comment by khuranakaran** [comment] 2015-12-10 07:40
@bretdabaker yes i am still getting same error just on Android M, unable to find any solution to it.

**Comment by bretdabaker** [comment] 2015-12-18 08:29
@khuranakaran We have removed dependency on `SYSTEM_ALERT_WINDOW` in v0.7.2 so it should not crash in Android M, if you are still getting the error then please verify you have updated the library.

**Comment by khuranakaran** [comment] 2015-12-18 08:41
@bretdabaker yes now the issue is resolved. It works perfect on Android M too.
Thankyou for your replies and time given in solving the issue.
